test-case1.py
Starting WinAppDriver...
Launching RMS Application...
Attaching to window handle: 0x4086c
Traceback (most recent call last):
  File "C:\Users\Test3\Desktop\automation\rms\test-case1.py", line 169, in <module>
    main()
  File "C:\Users\Test3\Desktop\automation\rms\test-case1.py", line 118, in main
    driver = attach_session_by_hwnd(hwnd)
  File "C:\Users\Test3\Desktop\automation\rms\test-case1.py", line 94, in attach_session_by_hwnd
    return webdriver.Remote(
  File "C:\Users\Test3\AppData\Roaming\Python\Python310\site-packages\appium\webdriver\webdriver.py", line 238, in __init__
    super().__init__(
  File "C:\Users\Test3\AppData\Roaming\Python\Python310\site-packages\selenium\webdriver\remote\webdriver.py", line 250, in __init__
    self.start_session(capabilities)
  File "C:\Users\Test3\AppData\Roaming\Python\Python310\site-packages\appium\webdriver\webdriver.py", line 329, in start_session
    response = self.execute(RemoteCommand.NEW_SESSION, w3c_caps)
  File "C:\Users\Test3\AppData\Roaming\Python\Python310\site-packages\selenium\webdriver\remote\webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Test3\AppData\Roaming\Python\Python310\site-packages\selenium\webdriver\remote\errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: Missing command parameter: appId

Stopping WinAppDriver...
